steps:
  # Deploy Cloud Functions
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    args: ['install']
  
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    args: ['run', 'build']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'functions'
      - 'deploy'
      - 'submitForm'
      - '--runtime'
      - 'nodejs20'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--source'
      - 'functions'
      - '--entry-point'
      - 'submitForm'
      - '--region'
      - 'us-central1'
  
  # Build and deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/talty-digital-frontend', './frontend']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/talty-digital-frontend']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'talty-digital-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/talty-digital-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
    waitFor: ['functions-deployment']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['functions', 'describe', 'submitForm']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['run', 'describe', 'talty-digital-frontend']
    id: 'functions-deployment'
    exitOnFailure: true

images:
  - 'gcr.io/$PROJECT_ID/talty-digital-frontend'
